baseURL = "https://www.back2code.me/"
languageCode = "en-us"
title = "Back 2 Code"
theme = "er"
googleAnalytics = "UA-127828717-1"
paginate = 20 

[Author]
    name = "Romain"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokailight"
    tabWidth = 2

[permalinks]
    post = "/:year/:month/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 10
    
[[menu.main]]
    name = "Archives"
    url = "/post/"
    weight = 20
