baseURL = "https://www.back2code.me/"
languageCode = "en-us"
title = "Back 2 Code"
theme = "er"
googleAnalytics = "UA-127828717-1"
disqusShortname = "back2code"
paginate = 12
summaryLength = 20

[params]
    since = 2016

[author]
    name = "Romain"

# https://gohugo.io/getting-started/configuration-markup/
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    noClasses = true
    style = "monokailight"
    tabWidth = 2

[permalinks]
    post = "/:year/:month/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 10
    
[[menu.main]]
    name = "Archives"
    url = "/post/"
    weight = 20
