baseurl = "/"
languageCode = "en-us"
title = "Back 2 Code"
theme = "ghostwriter"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"

[Author]
    name = "Romain"

[params]
    intro = true
    description = "[ Code — Data Science — Ops ]"
    headline = "Back 2 Code"
    github = "https://github.com/romainx"
    twitter = "https://twitter.com/r0mainx"
    stackoverflow = "https://stackoverflow.com/users/4413446/romain"
    
    opengraph = true
    shareTwitter = true
    shareFacebook = false
    shareGooglePlus = false
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = "highlight.pack.js"
    highlightJsLocalUrl = "highlight.pack.js"
  
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"



