baseurl = "/"
languageCode = "en-us"
title = "Back 2 Code"
theme = "hermit"
googleAnalytics = "UA-127828717-1"
disqusShortname = "back2code"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
pygmentsCodefences  = true
pygmentsUseClasses  = true
enableEmoji = true

[permalinks]
    post = "/:year/:month/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    
[[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 10

[Author]
    name = "Romain"

[taxonomies]
  tag = "tags"
  category = ""  # Categories are disabled by default.

[params]
    intro = true
    description = "[ Code — Data Science — Ops ]"
    headline = "Back 2 Code"
    homeSubtitle = "[ Code — Data Science — Ops ]"
    github = "https://github.com/romainx"
    twitter = "https://twitter.com/r0mainx"
    stackoverflow = "https://stackoverflow.com/users/4413446/romain"
    opengraph = true
    shareTwitter = true
    shareFacebook = false
    shareGooglePlus = false
    shareLinkedIn = false
    # Date
    dateFormat = "Jan 2, 2006"
    dateformShort   = "Jan 2"
    dateform        = "Jan 2, 2006"
    dateformNum     = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04 -0700"
    
    highlightJsUrl = "highlight.pack.js"
    highlightJsLocalUrl = "highlight.pack.js"
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/r0mainx"

  [[params.social]]
    name = "stackoverflow"
    url = "https://stackoverflow.com/users/4413446/romain"

  [[params.social]]
    name = "github"
    url = "https://github.com/romainx"
